FROM python:3.7-alpine

RUN apk add --no-cache --virtual=build-deps build-base && apk add --no-cache g++ libffi-dev

RUN pip install --upgrade pip && pip install locustio pyzmq
RUN apk del --no-cache build-deps

WORKDIR /locust
COPY scenario.py /locust/

ENTRYPOINT [ "/usr/local/bin/locust" ]
EXPOSE 8089 5557 5558